### ISSUE TITLE
Problem with Login

### ISSUE THREAD

**Issue by bigbak** [jamesnetherton/homehub-cli#11]
I've got:
BT Home Hub 5 (Type B) | Software version v0.07.06.01239-BT  | Last updated 13/3/2017

I've tried this on Windows and Ubuntu 16.0.4.
If I run without parameters and enter:
http://192.168.1.254
admin
mypassword

I get the following message.  

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x623733]

goroutine 1 [running]:
github.com/jamesnetherton/homehub-cli/vendor/github.com/jamesnetherton/homehub-c                             lient.(*Hub).Login(0xc4200aeb40, 0x14, 0xc4200118f0, 0x5)
        /home/ubuntu/.go_project/src/github.com/jamesnetherton/homehub-cli/vendo                             r/github.com/jamesnetherton/homehub-client/hub.go:188 +0x63
main.initCommands.func1(0xc420011880, 0x0, 0x1, 0x1, 0x1, 0x1, 0x1)
        /home/ubuntu/.go_project/src/github.com/jamesnetherton/homehub-cli/homeh                             ub-cli.go:85 +0x5e
github.com/jamesnetherton/homehub-cli/cmd.(*GenericCommand).Execute(0xc42004c070                             , 0xc420011880, 0x0, 0x1, 0x0, 0xc420011870, 0x5, 0xc420011801)
        /home/ubuntu/.go_project/src/github.com/jamesnetherton/homehub-cli/cmd/g                             eneric_command.go:68 +0x48
github.com/jamesnetherton/homehub-cli/cmd.(*GenericCommand).ExecuteLifecylce(0xc                             42004c070, 0xc420011880, 0x0, 0x1)
        /home/ubuntu/.go_project/src/github.com/jamesnetherton/homehub-cli/cmd/g                             eneric_command.go:44 +0xdb
github.com/jamesnetherton/homehub-cli/cli.(*CLI).Run(0xc4200ae620)
        /home/ubuntu/.go_project/src/github.com/jamesnetherton/homehub-cli/cli/c                             li.go:58 +0x232
main.main()
        /home/ubuntu/.go_project/src/github.com/jamesnetherton/homehub-cli/homeh                             ub-cli.go:35 +0x2cf_

**Comment by jamesnetherton** [comment]
These are the supported firmware versions:

https://github.com/jamesnetherton/homehub-cli/blob/master/matrix.md

Before logging in, you could try

`EnableDebug true`

Then see if anything obvious shows up in the HTTP response output when you try to login.

I don't have access to every type of router, so I can only verify against the hardware that I run.

I'd love to have contributions that could make this work across the different types of hardware. The client API is here if you're interested:

https://github.com/jamesnetherton/homehub-client

**Comment by bigbak** [comment]
Thanks.

I couldn't work out how to compare firmware versions.
The page request in debug is returning a 404. So not supported.

I'll look at the earlier shell script to see if I can modify that.

**Comment by jamesnetherton** [comment]
Closing this. There's a couple of open issues that should help to provide better feedback when faced with this scenario in future https://github.com/jamesnetherton/homehub-cli/issues/7 & https://github.com/jamesnetherton/homehub-client/issues/6.
