### ISSUE TITLE
Add support for changing WiFi channels

### ISSUE THREAD

**Issue by Interknet** [jamesnetherton/homehub-cli#14]
Could there be a way of making it capable of changing the channel of the wifi? I seem to have to change it sometimes because devices disappear on the 2.4GHz band and would like a quicker solution.

Not sure if this is the right place to put this or not, sorry if it isn't.

**Comment by jamesnetherton** [comment]
Nice idea - It should be doable. I'll take a look into adding this soon.

**Comment by jamesnetherton** [comment]
I released a [beta 0.5.0 release](https://github.com/jamesnetherton/homehub-cli/releases/tag/v0.5.0-beta1) which contains 4 new commands:

```
  WiFiFrequency24Ghz
  WiFiFrequency24GhzChannelSet
  WiFiFrequency5Ghz
  WiFiFrequency5GhzChannelSet
```

You can figure out what the current and available channels are for the 2.4GHz or 5GHz frequencies by running `WiFiFrequency24Ghz` or `WiFiFrequency5Ghz`.

You can modify the channel used by the frequency. E.g:

```
WiFiFrequency24GhzChannelSet 12
```

Or

```
WiFiFrequency5GhzChannelSet 12
```

**Comment by Interknet** [comment]
Sweet. I'll give it a go next time it kicks all the 2.4GHz devices off.  Thanks :D

**Comment by jamesnetherton** [comment]
0.5.0 release is now available which contains these modifications.
