### ISSUE TITLE
32 Bit?

### ISSUE THREAD

**Issue by Interknet** [jamesnetherton/homehub-cli#18]
Is it possible to have a 32 bit version? It'd be useful on a raspberry pi but it's ARM x86 architecture

**Comment by jamesnetherton** [comment]
Sure - I'll try and cut a new release over the weekend.

**Comment by jamesnetherton** [comment]
I just added arm (32Bit) and arm64 architectures to the v0.5.0 release page. Could you give it a try and let me know whether it works ok?

https://github.com/jamesnetherton/homehub-cli/releases/tag/v0.5.0
