### ISSUE TITLE
Add support for firmware SG4B1A006100

### ISSUE THREAD

**Issue by km09** [jamesnetherton/homehub-cli#19]
Is it possible to add support for fw SG4B1A006100?

Some commands work (logging in, public IP address, data sent/recvd) but output is 0 for DownstreamSyncSpeed & UpstreamSyncSpeed

```
k@homehub: DownstreamSyncSpeed
2018/08/09 00:18:49 [{"request":{"id":4,"session-id":"snip","priority":false,"actions":[{"id":0,"method":"getValue","xpath":"Device/DSL/Channels/Channel[@uid=\"1\"]/DownstreamCurrRate","options":{"capability-flags":{"interface":true}}}],"cnonce":499990591,"auth-key":"snip"}}]
2018/08/09 00:18:49 [POST /cgi/json-req HTTP/1.1
Host: 192.168.2.1
Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

req=%7B%22request%22%3A%7B%22id%22%3A4%2C%22session-id%22%3A%221192659787%22%2C%22priority%22%3Afalse%2C%22actions%22%3A%5B%7B%22id%22%3A0%2C%22method%22%3A%22getValue%22%2C%22xpath%22%3A%22Device%2FDSL%2FChannels%2FChannel%5B%40uid%3D%5C%221%5C%22%5D%2FDownstreamCurrRate%22%2C%22options%22%3A%7B%22capability-flags%22%3A%7B%22interface%22%3Atrue%7D%7D%7D%5D%2C%22cnonce%22%3A499990591%2C%22auth-key%22%3A%2272b2079e36ad5447685ab8048e7d1eb3%22%7D%7D]
2018/08/09 00:18:49 [HTTP/1.1 200 OK
Transfer-Encoding: chunked
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Wed, 08 Aug 2018 23:18:50 GMT
Expires: -1
Pragma: no-cache
Server: HTTP Server
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block

1ee
{"reply":{"uid":0,"id":4,"error":{"code":16777216,"description":"Ok"},"actions":[{"uid":1,"id":0,"error":{"code":16777238,"description":"Applied"},"callbacks":[{"uid":1,"result":{"code":16777238,"description":"Applied"},"xpath":"Device\/DSL\/Channels\/Channel[@uid='1']\/DownstreamCurrRate","parameters":{"value":0,"capability":{"name":"DownstreamCurrRate","description":"TBD","type":"xmo:uint32 xmo:number xmo:value","flags":{"value":true,"statistic":true,"xml-child":true}}}}]}],"events":[]}}
0

]
0
k@homehub:
```

**Comment by jamesnetherton** [comment]
It's a bit tricky without having the router & firmware to test against. 

At a guess this part of the request could be the problem `Device/DSL/Channels/Channel[@uid=\"1\"]/DownstreamCurrRate`. Maybe the DSL channel uid we're interested in is different.

I could experiment to see if there's a way of figuring out the correct DSL channel to use.

**Comment by jamesnetherton** [comment]
Also seems there are multiple ways of getting those states. E.g `Device\/IP\/Interfaces\/Interface[@uid='3']\/Stats\/BytesReceived`.

**Comment by jamesnetherton** [comment]
I made some tweaks that may help to fix the problem. 

Please can you try downloading one of the alpha releases below and testing the `DownstreamSyncSpeed` & `UpstreamSyncSpeed` commands?

[homehub-cli-linux.tar.gz](https://github.com/jamesnetherton/homehub-cli/files/2280154/homehub-cli-linux.tar.gz)
[homehub-cli-windows.zip](https://github.com/jamesnetherton/homehub-cli/files/2280152/homehub-cli-windows.zip)
[homehub-cli-darwin.tar.gz](https://github.com/jamesnetherton/homehub-cli/files/2280153/homehub-cli-darwin.tar.gz)

**Comment by km09** [comment]
Still outputting 0 with that version.

I've had a look into what I'm receiving in chrome when opening the status page, and seems it's slightly different:
```
{"uid":3,"id":2,"error":{"code":16777238,"description":"Applied"},"callbacks":[{"uid":1,"result":{"code":16777238,"description":"Applied"},"xpath":"Device\/FAST\/Lines\/Line[@uid='1']\/TestParams\/DownstreamCurrRate","parameters":{"value":317796,"capability":{"name":"DownstreamCurrRate","description":"TBD","type":"xmo:uint32 xmo:number xmo:value","flags":{"value":true,"statistic":true,"xml-child":true}}}}]},{"uid":4,"id":3,"error":{"code":16777238,"description":"Applied"},"callbacks":[{"uid":1,"result":{"code":16777238,"description":"Applied"},"xpath":"Device\/FAST\/Lines\/Line[@uid='1']\/TestParams\/UpstreamCurrRate","parameters":{"value":49969,"capability":{"name":"UpstreamCurrRate","description":"TBD","type":"xmo:uint32 xmo:number
```

`Device\/FAST\/Lines\/Line[@uid='1']` rather than `Device/DSL/Channels/Channel[@uid=\"1\"]`

I'd imagine that's because I'm on G.fast rather than VDSL, but could jsut be that they changed the terminology in this update?

**Comment by jamesnetherton** [comment]
I added some logic to use different XPath expressions depending on the firmware version. It should now use `Device/FAST/Lines` with your firmware.

Please could you download one of the builds below and test it again?

[homehub-cli-linux.tar.gz](https://github.com/jamesnetherton/homehub-cli/files/2280839/homehub-cli-linux.tar.gz)
[homehub-cli-windows.zip](https://github.com/jamesnetherton/homehub-cli/files/2280837/homehub-cli-windows.zip)
[homehub-cli-darwin.tar.gz](https://github.com/jamesnetherton/homehub-cli/files/2280838/homehub-cli-darwin.tar.gz)

**Comment by km09** [comment]
All seems to be working perfectly with that version, thanks!
