### ISSUE TITLE
Does not return WiFi Devices

### ISSUE THREAD

**Issue by smileham** [jamesnetherton/homehub-cli#20]
homehub-cli ConnectedDevices only returns ethernet devices

(I note that it looks like there may be a typo in the connected_devices.go code when filtering for WiFi devices?)

**Comment by jamesnetherton** [comment]
Thanks for reporting, there's a new 0.7.0 release containing a fix for this:

https://github.com/jamesnetherton/homehub-cli/releases/tag/v0.7.0
