### ISSUE TITLE
HomeHub versions

### ISSUE THREAD

**Issue by pgleghorn** [jamesnetherton/homehub-cli#32]
Hi, do you know which of these HomeHub versions this project is expected to work with?
https://www.bt.com/help/broadband/learn-about-broadband/different-types-of-bt-hub

(edit: Should really have posted this question against the underlying client https://github.com/jamesnetherton/homehub-client )

Thx
Phil

**Comment by jamesnetherton** [comment]
It works for sure with the BT Smart Hub, not sure about the HomeHub 3, 4 & 5.

It definately does not work with the BT Smart Hub 2 as it has a completely different API.

If it helps, there's a [compatibility matrix](https://github.com/jamesnetherton/homehub-cli/blob/master/matrix.md) which is a bit out of date now, but it lists the compatible firmware versions. There's one at the [client project](https://github.com/jamesnetherton/homehub-client/blob/master/matrix.md) too.
